### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

### ISSUE THREAD

**Issue by Bethel204** [ub-nsf-hsi/shasta-ub#23]
Hi,
Please I encountered an error while trying to install Shasta. What is the solution please? this is the error:
pip install --upgrade pip setuptools
Requirement already satisfied: pip in /home/ugochukwu/myenv/lib/python3.12/site-packages (24.0)
Requirement already satisfied: setuptools in /home/ugochukwu/myenv/lib/python3.12/site-packages (70.0.0)
(myenv) ugochukwu@ugochukwu-VMware-Virtual-Platform:~/shasta-ub$ python setup.py install
Traceback (most recent call last):
  File "/home/ugochukwu/shasta-ub/setup.py", line 7, in <module>
    with open('README.rst') as readme_file:
![shasta error](https://github.com/ub-nsf-hsi/shasta-ub/assets/171604936/ebac3fb9-63f6-4348-ba28-64e0b6e1c2a5)

         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

```

**Comment by HemuManju** [comment]
@Bethel204, the bug has been fixed. Can you try to setup now?

**Comment by Bethel204** [comment]
Ok thank you so much, please can I run it on Python 3.8? Before now it was giving error. Bpy could not install.
________________________________

**Comment by HemuManju** [comment]
There are no [bpy](https://pypi.org/project/bpy/3.4.0/) compatible versions with python 3.8. If you want you can upgrade python and install the package. I have removed the hard bpy requirement. Expect for preprocessing (where new environment are created) bpy is not used anywhere.

**Comment by Bethel204** [comment]
Thank you so much, I am very grateful for the information. I will let you know of the outcome.
________________________________
